### ISSUE TITLE
Не загружает более 200 баров

### ISSUE THREAD

**Issue by rooler3** [WISEPLAT/backtrader_bybit#1]
Не загружает более ~200 баров( 5 минутный фрейм примерно 16 часов), хотя на бинансе загружает

**Comment by WISEPLAT** [comment]
не загружает на bybit? или binance?

**Comment by WISEPLAT** [comment]
> Не загружает более ~200 баров( 5 минутный фрейм примерно 16 часов), хотя на бинансе загружает

fixed https://github.com/WISEPLAT/backtrader_bybit/commit/5b7a92be8d474fea92c73c9a4a41dece4674a1c8
Thanks))
